### PR TITLE
remove unmaintained github-markdown gem

### PR DESCRIPTION
**Pull request by akostadinov**

### CODE REVIEW

**Comment by mayorova** [comment]
What was this gem used for?...

**Comment by akostadinov** [comment]
I couldn't find any usages so running the tests to see if anything failed. We use markdown as an alternative syntax for dev portal but we seem to be using redcarpet

**Comment by mayorova** [comment]
We probably can remove this hack. https://github.com/3scale/porta/blob/db75972a250699af2d4a17284fb40a8ec5edae4c/app/models/authentication_provider.rb#L52

And I guess this also: https://github.com/3scale/porta/blob/db75972a250699af2d4a17284fb40a8ec5edae4c/osx-manual-setup.md?plain=1#L159

**Comment by akostadinov** [comment]
About this one, how else should it be implemented? Do you know what it does? I will investigate if not.

https://github.com/3scale/porta/blob/db75972a250699af2d4a17284fb40a8ec5edae4c/app/models/authentication_provider.rb#L52

**Comment by jlledom** [comment]
> About this one, how else should it be implemented? Do you know what it does? I will investigate if not.
> 
> https://github.com/3scale/porta/blob/db75972a250699af2d4a17284fb40a8ec5edae4c/app/models/authentication_provider.rb#L52

I think this is the right way:

```ruby
  AVAILABLE = {
    account_types[:developer] => [Keycloak, Auth0, GitHub],
    account_types[:provider]  => [Keycloak, Auth0]
  }.with_indifferent_access.freeze
  private_constant :AVAILABLE

  def self.available(account_type = account_types[:developer])
    AVAILABLE[account_type]
  end
```

You don't need to prepend `AuthenticationProvider::` before `GitHub`.

**Review by jlledom — COMMENTED** [review]
I haven't found where this is used. Agreed on removing it.

**Comment by akostadinov** [comment]
I actually don't like gambling with namespaces. I prepended `self::` to the items and be sure these don't leak from somewhere else. PTAL

**Review by jlledom — APPROVED** [review]

**Pull request merged**
