### PR TITLE
Remove unsupported feature: logos

### PR DESCRIPTION
**Pull request by Martouta**
Remove all its code. Et voilà:
image

### CODE REVIEW

**Comment by Martouta** [comment]
@guicassolato I've just asked @3scale/product if they know about this and if they need a Jira issue 🤔 let's see what they say. I'll post the conclusions here 😄

**Comment by Martouta** [comment]
Andreu said he thinks no need for JIRA issue if this is inside the UI/UX changes, but he will speak with Thomas 😄

**Comment by andreumasferrer** [comment]
From previous conversations, I though users will continue seeing their logo on the sign in page, hence the option for setting the logo would remain. @thomasmaas , let's clarify when you have a minute. :-)

**Comment by thomasmaas** [comment]
Sign in page will indeed have the logo for a couple of days more but I'm aiming to give it a PatterFly 3 make over, meaning it will disappear from there as well. We are not deleting any uploaded logo's and, for now the feature will stay available through the API.

**Comment by Martouta** [comment]
Imo we should remove it from the API as well. Although no time for today, but it could be done for ER1.
WDYT @thomasmaas and @andreumasferrer ?

**Comment by thomasmaas** [comment]
agreed for ER1, it will also be removed from sign in page for ER1. Only possible risk I see with removing database row: Saas customers might be using it to power their dev portal logo. I don't think it makes sense but they could…

**Comment by Martouta** [comment]
Maybe we have a way to check if they do 🤔

**Pull request merged**
