### PR TITLE
Configure the Github app to prevent us for merging PRs to check for certain words in the title

### PR DESCRIPTION
**Pull request by Martouta**
Before this used to be the default behaviour, but now by default it only checks for `WIP` in the title, so in order to check for `Do not merge` as well, which is not the same concept, we need this config file as  you can find at the moment in https://github.com/wip/app#configuration

### CODE REVIEW

**Comment by Martouta** [comment]
@josemigallas Done 😎 💃

**Comment by guicassolato** [comment]
I know this has been merged already, but I don't think it is the right way to go. If something is no longer "WIP", it should NOT be prevented from merging.

**Comment by mikz** [comment]
@guicassolato WIP will remove the red status when "WIP" is removed from the title.

**Comment by Martouta** [comment]
I will revert this as we spoke in Slack. I leave track here of the talk 👍 
image
image
image
image
image
image

**Comment by mikz** [comment]
To summarize lengthy conversation: Let's just use *WIP*.

**Comment by hallelujah** [comment]
Just use WIP anyway other features are paid so unlikely to work

**Comment by Martouta** [comment]
Ok with using just **WIP** and with the summary of the conversation 👍 , but just to be clear, @hallelujah , this is completely free anyway 😜 The decision about this has nothing to do with the price then 😄

**Pull request merged**
