### PR TITLE
enabled codeclimate check

### PR DESCRIPTION
**Pull request by nidhi-soni1104**
This PR enables the code climate issue

### CODE REVIEW

**Comment by hallelujah** [comment]
@nidhi-soni1104 Which issue is it?

**Comment by jsmadis** [comment]
@hallelujah It was introduced as last commit in the #2646 
https://github.com/3scale/porta/pull/2646/commits/a92ed9754348b6e51704e83fd020a9b674afa347

**Review by hallelujah — CHANGES_REQUESTED** [review]
@jsmadis @nidhi-soni1104 

I'd prefer sticking to good coding guide. Instance variables are more error prone in helpers:

- subjected to be `nil` because of a typo
- sometimes `@service` refers to the model, sometimes to a decorator/presenter, leading to hard NoMethodError fix
- re-using helpers will become difficult

**Review by hallelujah — APPROVED** [review]
Sorry I misread

**Pull request merged**
