### PR TITLE
[WIP][DO NOT EVER MERGE THIS PR] Checking what is wrong in CircleCI for #717

### PR DESCRIPTION
**Pull request by Martouta**
I will remove this PR, I just want to know what's wrong with https://github.com/3scale/porta/pull/717
It works locally but it is failing in CircleCI, and I am checking why 😄

### CODE REVIEW

**Comment by Martouta** [comment]
Mission accomplished 😄

**Comment by Martouta** [comment]
Not needed anymore 😄

**Comment by hallelujah** [comment]
@Martouta so what's wrong with CircleCI? Could you explain what did you find?

**Comment by Martouta** [comment]
@hallelujah Nothing is wrong with CircleCI, it was wrong with my PR 😄 and I wasn't reproducing it locally originally because I was using a different configuration locally 😉

**Comment by Martouta** [comment]
And I didn't explain anything here because I simply fixed the bug in the code in the original PR (and here) and closed this when I understood the problem 😄

**Comment by Martouta** [comment]
@hallelujah In case that you want more details, what was happening is I had some cucumbers failing for 2 reasons with the feature enabled for all tests:
1. I wasn't stubbing the connection request to an external service
2. Some cucumbers of creation of accounts where failing, but they worked when I added a "And I wait for 5 seconds" to see if it was because it takes a bit longer.
So I just disabled the feature for all tests except for those that I need it and in those I stubbed the feature. This way it is faster 😄

**Pull request closed without merging**
