### PR TITLE
Made minor UI Changes to Services - New and Index Pages

### PR DESCRIPTION
**Pull request by motaparthipavankumar**
**What this PR does / why we need it**:

This PR fixes minor UI grammatical and alignment issues. 

**Which issue(s) this PR fixes** 

This fixes typos and alignment, so there is no issue logged for this.

**Verification steps** 
Scenario 1: Go to default Developer portal > Services > Verify the table alignment is correct and the final table header (Subscribe) is appropriate.

**Note**: To test the below scenario, we need to first create/update API, with more than one service plans.

Scenario 2: Go to default Developer portal > Services > Under Subscribe column, choose a service which has more than one Service Plan, then it will take you to a view to Subscribe to a service with a plan - Make sure everything looks good and makes sense.

**Special notes for your reviewer**:
**Scenario 1 Reference Screenshot:** 
Screenshot from 2019-04-29 14-26-56

**Scenario 2 Reference Screenshot:** 
Screenshot from 2019-04-26 15-37-46

### CODE REVIEW

**Comment by thomasmaas** [comment]
Thank you for your pull request!

Some remarks:
- Could you paste screenshots of styles your fixing: before, after?
- We should not edit the bootstrap css file so if style changes need to be made it would need to be somewhere else.
- consider splitting text updates and style updates in 2 different pull requests

**Comment by Martouta** [comment]
Thanks 👍 💪 
Please also [sign all your commits](https://github.com/3scale/porta/blob/master/CONTRIBUTING.md#is-there-any-other-requirement-to-open-a-pr).

**Comment by motaparthipavankumar** [comment]
In the new PR's listed below attached before and after screenshots.
Updated the styling changes in the default.css file instead of bootstrap.css.

Created Two PR's - 
Text updates https://github.com/3scale/porta/pull/811
Styling updates https://github.com/3scale/porta/pull/810

Yet to sign the comments, so added [WIP] to PR's, will update it once i sign the commits.

**Comment by hallelujah** [comment]
Sorry, it seems your work did not get enough attention to us.
Thank you for making this project better.

We are going to close it as it was stale for too long.

**Pull request closed without merging**
