### PR TITLE
Update codecov uploader

### PR DESCRIPTION
**Pull request by mayorova**
**What this PR does / why we need it**:

The Codecov bash uploader is deprecated, and (related or not) it was not working consistently lately. 

Te documentation and the migration path are documented here: https://docs.codecov.com/docs/deprecated-uploader-migration-guide

For this PR I've chosen the CircleCI Orb: https://circleci.com/developer/orbs/orb/codecov/codecov

**Which issue(s) this PR fixes** 

-none-

**Verification steps** 

Run the full CircleCI pipeline and ensure that the results are uploaded.

**Special notes for your reviewer**:

The latest version of the codecov CircleCI orb is 4.2.0. However, it fails with the following error:
```
[PYI-364:ERROR] Failed to load Python shared library '/tmp/_MEI0P0UrX/libpython3.11.so.1.0': dlopen: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEI0P0UrX/libpython3.11.so.1.0)
```

Looks like version `3.3.0` works on our builder image. Maybe after we upgrade to RHEL9, it will work. Also, not sure if `3.3.0` is the right way, because of what the release notes say: https://github.com/codecov/codecov-circleci-orb/releases/tag/v4.0.0

> Version 4.0.0 of the CircleCI orb represents a move to using the new [Codecov CLI](https://docs.codecov.com/docs/the-codecov-cli) over the [Codecov uploader](https://docs.codecov.com/docs/codecov-uploader).

I am not quite sure whether it actually uses CLI or the bash uploader... but looking at the diff between the versions, I'd say it's CLI already.

But anyway, it seems to be working, so it's an improvement.

### CODE REVIEW

**Review by akostadinov — APPROVED** [review]

**Review by jlledom — COMMENTED** [review]
I can see the steps that upload the report, but where can I see the report?

**Comment by mayorova** [comment]
> I can see the steps that upload the report, but where can I see the report?

Well, in the logs of the Codecov step there a the link to the results for each commit, e.g. https://app.codecov.io/github/3scale/porta/commit/8003ad727b102f3626d95ffe584da5066f4b755b

But I can see there are some errors :melting_face: 
image

**Comment by akostadinov** [comment]
> Unusable report due to issues such as source code unavailability, path mismatch, empty report, or incorrect data format. Please visit our troubleshooting document
for assistance.

image

**Comment by akostadinov** [comment]
But this is just single report. And maybe the first one. Seems like a glitch.

**Comment by akostadinov** [comment]
Maybe we need to (re)enable github integration?

**Comment by jlledom** [comment]
I tried to run all pipelines because the codecov test report appears magically here in the PR only when all pipelines pass, but... cucumbers failed for oracle. Anyway, if yo manage to generate a report that works without errors, LGTM.

**Comment by mayorova** [comment]
> But this is just single report. And maybe the first one. Seems like a glitch.

I think this is because we were not generating coverage data for jest tests. I added it in the last comment, and I think it should work fine now - but the tests haven't finished yet.

**Review by jlledom — APPROVED** [review]
It seems reports are fixed now

**Comment by mayorova** [comment]
> Maybe we need to (re)enable github integration?

Do you refer to Codecov checks? Do you know how to configure them? :upside_down_face:

**Pull request merged**
