### PR TITLE
⚰️ Cleanup partial apicast

### PR DESCRIPTION
**Pull request by josemigallas**
https://issues.redhat.com/browse/THREESCALE-7992

### CODE REVIEW

**Comment by akostadinov** [comment]
Who should review this?

**Comment by josemigallas** [comment]
> Who should review this?

Ah! An unsuspecting volunteer!

**Comment by akostadinov** [comment]
I just don't understand how is this to be tested. What is the effect of the change?

**Comment by josemigallas** [comment]
@akostadinov This is supposed to be dead code that should have been removed as part of [THREESCALE-3759](https://issues.redhat.com/browse/THREESCALE-3759). Not sure how to test it though, I guess all related tests were removed.

Maybe @hallelujah @guicassolato know more.

**Review by akostadinov — DISMISSED** [review]
Ok. If it doesn't result in any side effects in the UI, it should be fine.

**Comment by josemigallas** [comment]
> Ok. If it doesn't result in any side effects in the UI, it should be fine.

Well, it turns out it does breaks the UI 😅

**Pull request merged**
