### PR TITLE
[tests] Run all tests in random order

### PR DESCRIPTION
**Pull request by hallelujah**
It is time to make the tests order independent

### CODE REVIEW

**Comment by akostadinov** [comment]
I've seen tests being split randomly already but maybe because of the circleci scripts...
But also perhaps not random within the files. So besides minor issues I expect things to be fine with random order. +1

**Comment by mayorova** [comment]
Yes @akostadinov I was also surprised when I saw this PR (I dug it out of the grave).

Looks like the tests do break because of this, by the way :sweat_smile:

**Comment by akostadinov** [comment]
Just a couple of units and cucumbers. The integration one failed for environmental issues. Well there might be some more that we don't know yet because of order. But it doesn't look terrible. Seems like a feasible task.

**Comment by jlledom** [comment]
> Looks like the tests do break because of this, by the way 😅

Then the tests are wrong!

**Pull request closed without merging**
