### PR TITLE
Updates for PR #3103

### PR DESCRIPTION
**Pull request by mayorova**

### CODE REVIEW

**Comment by akostadinov** [comment]
Seems like this needs a rebase.

**Comment by mayorova** [comment]
@akostadinov 
Yeah... the list of commits is weird. I guess it's a result of merging master.

Makes sense to clean it up.

**Comment by akostadinov** [comment]
Not only list of commits but it seems more files are reported changed than they really are.

**Comment by mayorova** [comment]
@akostadinov More files are because of merging master.
Once merged into `THREESCALE-3927-update-to-openapi` I guess they won't be shown in the diff, because they will not change anything in master.

**Comment by mayorova** [comment]
OK @akostadinov cc @nidhi-soni1104 

I removed the "merge" commit from this PR, so it only adds some extra things on top of the original https://github.com/3scale/porta/pull/3103

I suggest to restore the conflicts with master on the original PR https://github.com/3scale/porta/pull/3103

I just didn't want to rebase the PR of a different author, I consider it kind of "rude" :grimacing: .

But it's a must to merge/rebase to be able to test the CMS API, specifically these changes need to be incorporated: https://github.com/3scale/porta/pull/3136/files

**Pull request merged**
