### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by gsaslis**

### CODE REVIEW

**Comment by gsaslis** [comment]
Due to the unsigned commit issue, i've now opened a new PR that basically does the same thing. 

https://github.com/3scale/porta/pull/24

However, I suspect if we squash & merge, the single commit will be signed??

**Comment by Martouta** [comment]
I don't see why you need a new PR @yorgos, although I don't find it a problem either 😊 but I think you could cherry-pick in your old branch the commit of the new one and remove that commit you don't like 🤔

**Comment by hallelujah** [comment]
@gsaslis You can if your commits are signed with `git log --show-signature` before pushing

**Comment by gsaslis** [comment]
@hallelujah yeah i know, but :  https://github.com/3scale/porta/pull/15#issuecomment-423055425

@Martouta i opened a new PR because "Merging is blocked. The base branch requires all commits to be signed" and mine wasn't, so it was just easier for the kinds of changes we're talking about here (also, the new PR is easier to review than this one). 
In any case, that's why I asked if anyone knows about squashing the commit... 

anyway, closing this ;)

**Comment by guicassolato** [comment]
> Due to the unsigned commit issue, i've now opened a new PR that basically does the same thing.
> 
> #24
> 
> However, I suspect if we squash & merge, the single commit will be signed??

Try rebasing next time.

**Pull request closed without merging**
