### PR TITLE
Remove React specs from app folder

### PR DESCRIPTION
**Pull request by josemigallas**
- Moving everything spec-wise from `app/javascript` into `spec/javascripts`.
- Also keeping the __mocks__ folder name to stay in line with Jest standards.
- Also changing import strategy to avoid long import sentences in specs and make them location-independent.

### CODE REVIEW

**Comment by mikz** [comment]
Is it application code? I think it is more testing code no? So it should not live there. But thats just my 2ç.

**Comment by josemigallas** [comment]
> Is it application code? I think it is more testing code no? So it should not live there. But thats just my 2ç.

In react code, tests are located alongside source code so in this particular case I see it as a good place. I still wonder if it would be better with the underscores, since it's a jest convention (kinda).

**Comment by josemigallas** [comment]
> @josemigallas This also means this is going to be distributed with the application code to our clients. Not cool.

That's been (or should be) taken care by Webpack when building the production bundle.

**Comment by mikz** [comment]
@josemigallas we ship `app` folder in the image. We don't ship `spec` or `test`. Because rails consider "app" to be the application code. Webpack is not going to help here.

**Comment by didierofrivia** [comment]
@mikz true that we are not delivering `spec` and `test` folders, makes total sense. Now we are placing the tests alongside the js source. Both of them reside in `app/javascript/src` because that was the default webpack suggested. What we could do in the near future, is place all js tests in either of those ignored (not shipped) folders. It could be done as part of https://github.com/3scale/porta/pull/57

**Comment by josemigallas** [comment]
> You can configure jest to find where your tests are:
> 
> ```
> "jest": {
>   "roots": [
>     "spec/javascripts"
>   ]
> },
> ```
I would happily do these changes here @didierofrivia @hallelujah

**Comment by didierofrivia** [comment]
@josemigallas : +1:

**Comment by mikz** [comment]
@josemigallas master is ready to be build from forks now, rebasing should make the CircleCI build green.

**Comment by didierofrivia** [comment]
This is included in https://github.com/3scale/porta/pull/57

**Pull request closed without merging**
