### PR TITLE
Revert "Bump commonmarker from 0.21.0 to 0.23.6"

### PR DESCRIPTION
**Pull request by jlledom**
Reverts 3scale/porta#3069

Ruby 2.4 is not supported anymore.

### CODE REVIEW

**Review by josemigallas — DISMISSED** [review]

**Comment by mayorova** [comment]
Shouldn't we add a version specifier (for max version) in Gemfile?

**Comment by jlledom** [comment]
> Shouldn't we add a version specifier (for max version) in Gemfile?

If any, I would lock to the major 0.x.x, but I wouldn't set a max version to keep it under ruby 2.4, because we'll probably forget to remove the restriction when we migrate to OCP with ruby 2.6

**Comment by mayorova** [comment]
We can open a JIRA to upgrade this and other gems ones we're off Ruby 2.4

**Comment by jlledom** [comment]
> We can open a JIRA to upgrade this and other gems ones we're off Ruby 2.4

Ok, I set the max version.

**Review by thalesmiguel — APPROVED** [review]

**Pull request merged**
