### PR TITLE
Add info about Rails cache to INSTALL.md

### PR DESCRIPTION
**Pull request by jlledom**
**What this PR does / why we need it**:

It adds a new section to INSTALL.md to show how to enable the rails cache for development

### CODE REVIEW

**Comment by akostadinov** [comment]
It is enabled by default in `config/examples/cache_store.yml`. The example configs is something everybody is expected to use unless they have special needs.

**Comment by jlledom** [comment]
AFAIK it's disabled by default, because it only uses that configuration when the file `tmp/caching-dev.txt` exists; otherwise it uses `:null-store`. See https://github.com/3scale/porta/blob/master/config/environments/development.rb#L31

**Comment by akostadinov** [comment]
We have it set also in `config/application.rb`. I'm not sure which option takes precedence.

**Comment by jlledom** [comment]
I think it takes the value from `config/application.rb` when it's enabled, and sets the value to `:null_store` when disabled. See https://github.com/3scale/porta/blob/master/config/environments/development.rb#L36

This is what I see in my local environment

```
$ bundle exec rails dev:cache
Development mode is now being cached.
$ bundle exec rails c
Loading development environment (Rails 5.2.8)
[1] pry(main)> Rails.application.config.cache_store
=> [:mem_cache_store, ["localhost:11211"], {}]

$ bundle exec rails dev:cache
Development mode is no longer being cached.
$ bundle exec rails c
Loading development environment (Rails 5.2.8)
[1] pry(main)> Rails.application.config.cache_store
=> :null_store
```
So the default value depends on the presence of `tmp/caching-dev.txt` when you run rails for the first time after cloning the repo, which I assume is false since that folder is empty in the repo.

**Comment by akostadinov** [comment]
I understand that this is the default for Rails, but is we want to have it enbaled in general, why don't we change config to make it always enabled only depending on the configuration file?

Enabling by reading the docs doesn't seem very reliable and then if one loses the `tmp` dir or setup new environment, it would be easy to forget.

**Comment by jlledom** [comment]
In my opinion is better to work having it enabled, but if we update the config file to enable it by default, then the `bundle exec rails dev:cache` won't have any effect anymore and the only way to disable the cache locally would to update the config file again and have the file bothering in the git index and potentially being commited by mistake. If somebody in the team knows how to enable the cache by default without leaving any trace in the git index, I'd go for it.

**Comment by akostadinov** [comment]
`/config/cache_store.yml` is in `.gitignore` already.

**Comment by jlledom** [comment]
If I'm not wrong, this is how it works:

1. [cache_store.yml](https://github.com/3scale/porta/blob/e7845856a42cc58a85376568c11b1df72e5cb56b/config/examples/cache_store.yml#L1): Contains the date for the default cache store, in this case memcached.
2. [application.rb](https://github.com/3scale/porta/blob/e7845856a42cc58a85376568c11b1df72e5cb56b/config/application.rb#L155): Reads `cache_store.yml` to get the cache params and configures a default cache store in rails. This doesn't mean it's enabled, only configured.
3. [development.rb](https://github.com/3scale/porta/blob/e7845856a42cc58a85376568c11b1df72e5cb56b/config/environments/development.rb#L31): This enables or disables the default cache store based on the presence of the file `tmp/caching-dev.txt`

So AIUI updating cache_store.yml would be useful to switch to another cache store different from memcache, but not for enable or disable it.

**Comment by akostadinov** [comment]
If we use `:null_store`, does it matter that `config.action_controller.perform_caching = true`?

My line of thinking is that with `null_store` there will be no caching anyway. Should be very rare if ever to need `config.action_controller.perform_caching = false` for this to be a problem.

Or do you see more benefits to keep using `rails dev:cache` as your original suggestion goes?

**Comment by akostadinov** [comment]
btw we may implement logic to disable caching when `null_store` is used but that would be an over-engineering as I see it.

**Comment by jlledom** [comment]
You're right. We can leave it always enabled in `development.rb`, and then use `cache_store.yml` to set the store to `memcache` or null, using `memcache` as default as it's now. That would work and not mess with the git index. So I'd say we have two options:

- Leaving as it is:
  - Pros: It can be enabled/disabled by `rails dev:cache` which is the standard way and documented in the official Rails docs
  - Cons: Disabled by default
- Enable it by default and allow contributors to disable by through `cache_store.yml`
  - Pros: Enabled by default
  - Cons: Not the standard way

I prefer to follow the standard but don't have a strong opinion. Should we ask the team?

**Comment by akostadinov** [comment]
I don't see it as a problem. This standard does not make so much sense to me in case we want some other default. Also the rake task can be overridden to fails and print a message that you control caching by editing the file. It should not confuse anybody in that way.

You were the driver behind this. So you decide what to do. If you want, I'm ok to just go ahead with the change. If you in doubt, asking the rest of the team is good with me too.

**Comment by jlledom** [comment]
In that case, I prefer to follow the standard. I think that's always the best choice, and enabling the cache it's just one command, not a big deal.

**Comment by akostadinov** [comment]
When I wrote
> If you want, I'm ok to just go ahead with the change. If you in doubt, asking the rest of the team is good with me too.

I meant that if you want, you can make this enabled by default. I didn't mean that doc-only change is fine with me. Sorry if I was not clear.

I believe nobody would notice this doc and remember to do it. I don't see any benefits in requiring a manual step. 

I differentiate between a standard functionality in rails and a "standard". It is standard in Rails that memcached is **not** used in dev mode, yet you want it enabled. One can argue that it's against the standard. So you want us to stop following the standard but do it manually and have to think about it, instead of making things work as we want OOB. I know for sure that if something depends on my memory, then I can guarantee you that immediately or very soon I stop thinking about it and forget it. And I don't know people that always remember everything, although many people are better "rememberers" than me but some are even worse.

That's why I don't agree with a doc-only change.

**Comment by jlledom** [comment]
I pushed the changes to have it enabled by default

**Review by akostadinov — APPROVED** [review]

**Pull request merged**
