### PR TITLE
THREESCALE-10915: Fix Quick starts images in production mode

### PR DESCRIPTION
**Pull request by mayorova**
**What this PR does / why we need it**:

In production mode Quick starts images are not showing: 
Screenshot from 2024-05-17 11-46-07

This is an alternative (and simpler) to the fix proposed in https://github.com/3scale/porta/pull/3729

The main issue is that the images were passing through the assets pipeline, and were added to the public assets folder with the fingerprint suffix, like this:
```
/public/assets/quickstarts/learn-about-products-afa799f1e9d67800ea82cdb113e2cf11e624d331f36818ab496c3a3f6d9f8934.png
```
However, there is no obvious way to reference these images from the Quick start's YAML definition, as we don't have direct access to `image_tag` helper (or at least I couldn't find a way...).

As these images are only used from Quick starts, I thought it was fine to just copy them as static assets in the `public` folder.

Maybe there is some better way, but I don't know it :) 

The PR also removes some duplicate images from the repo.

There is also this issue on the Quickstarts repo that seems relevant: https://github.com/patternfly/patternfly-quickstarts/issues/207

**Which issue(s) this PR fixes** 

https://issues.redhat.com/browse/THREESCALE-10915

**Verification steps** 

- configure porta for running in production mode
- precompile assets
- run Rails server in production mode
- verify that the images are visible in Quickstarts

**Special notes for your reviewer**:

### CODE REVIEW

**Review by jlledom — APPROVED** [review]
Tried locally and it works.

IMO this is better than https://github.com/3scale/porta/pull/3797 because it's more simple. However, Webpack could add a fingerprint to image names to invalidate the browser cache in case we update the images. That would be the optimal approach IMO.

**Review by jlledom — COMMENTED** [review]
I suggest to remove `app/assets/images/quickstarts`. This is being taken by Sprockets to generate the digested images under `public/assets/quickstarts`. But we don't need to generate those anymore, now the images are at `public/quickstarts/images/`.

**Comment by mayorova** [comment]
> I suggest to remove `app/assets/images/quickstarts`. This is being taken by Sprockets to generate the digested images under `public/assets/quickstarts`. But we don't need to generate those anymore, now the images are at `public/quickstarts/images/`.

Hmm, I don't have this folder :thinking: I do have `app/assets/images`, but not `quickstarts` inside of it.

**Comment by mayorova** [comment]
> But for some reason it's not in `fix-missing-quickstarts-images`. I guess it got removed in some previous commit, but I don't know what will happen when you merge this, will the images there be kept or be removed?

Ah, no, I see what happened :)

Those images in `app/assets/images/quickstarts` were moved to `public/quickstarts/images` :) 
Screenshot from 2024-05-30 10-16-37



And in fact, I don't know if this path is good or it should be just `public/quickstarts`, or `public/images/quickstarts` :shrug:

**Comment by jlledom** [comment]
> Those images in `app/assets/images/quickstarts` were moved to `public/quickstarts/images` :) 

Fine.

> And in fact, I don't know if this path is good or it should be just `public/quickstarts`, or `public/images/quickstarts` 🤷

I don't think it's so important, `public/quickstarts/images` is good enough.

**Review by josemigallas — APPROVED** [review]

**Pull request merged**
