### PR TITLE
Add RedHatFont to porta

### PR DESCRIPTION
**Pull request by damianpm**
**What this PR does / why we need it**:

Using [RedHatFont](https://github.com/RedHatOfficial/RedHatFont) in Porta

**Which issue(s) this PR fixes** 

https://issues.redhat.com/browse/THREESCALE-4168

Deployed in [preview](https://multitenant-admin.preview01.3scale.net/p/admin)

### CODE REVIEW

**Comment by thomasmaas** [comment]
Vertical navigation links get bold on click, which makes for a noisy experience.

**Comment by damianpm** [comment]
>     * Vertical navigation links get bold on click, which makes for a noisy experience.
> 
>     * Would like to see dev portal wrapper but doesn't work in preview

* The bold on click is PF4 default: https://www.patternfly.org/v4/documentation/react/components/nav
* Dev Portal wrapper screenshots:
Screenshot 2019-12-19 at 19 17 22

Screenshot 2019-12-19 at 19 18 05

Screenshot 2019-12-19 at 19 18 33

@thomasmaas ☝️

**Comment by thomasmaas** [comment]
- We don't have the behavior currently, how could this pr change that?
- i meant the preview wrapper:
Screenshot 2019-12-19 19 23 32

**Comment by damianpm** [comment]
>     * We don't have the behavior currently, how could this pr change that?
> 
>     * i meant the preview wrapper:
> 

No, misunderstanding, I was talking about the dev portal section (not shown in preview env):
dev-portal

The Dev Portal wrapper is like this:
Screenshot 2019-12-19 at 19 36 15

@thomasmaas

**Comment by thomasmaas** [comment]
@damianpm seems like they changed the PF4 behavior with regard to bold links in vertical nav: https://www.patternfly.org/v4/documentation/react/components/nav

**Pull request merged**
