### PR TITLE
🦋 Update Notification Preferences page

### PR DESCRIPTION
**Pull request by josemigallas**
[THREESCALE-11419: Account Settings > Personal > Notification preferences](https://issues.redhat.com/browse/THREESCALE-11419)

### Before
Screenshot 2024-10-14 at 12 10 37

Screenshot 2024-10-11 at 12 51 26

### After
Screenshot 2024-10-14 at 12 01 35

Screenshot 2024-10-14 at 12 08 12

### CODE REVIEW

**Review by mayorova — APPROVED** [review]

**Comment by mayorova** [comment]
I don't like how there is less space between the description and the **next** checkbox than between the description and **its own** checkbox, but I guess this is just how PF4 is... :shrug:

**Comment by josemigallas** [comment]
> I don't like how there is less space between the description and the **next** checkbox than between the description and **its own** checkbox, but I guess this is just how PF4 is... 🤷

Yeah it looks off... I will take a look.

**Comment by mayorova** [comment]
> Yeah it looks off... I will take a look.

Yeah, but I've checked on https://pf4.patternfly.org/components/checkbox/#with-description
and copy-pasting the example checkbox several times gives the same result :shrug: 

So, I think it's a Patternfly thing... I guess we shouldn't fix it with custom CSS, so... that's fine.

**Comment by josemigallas** [comment]
> > Yeah it looks off... I will take a look.
> 
> Yeah, but I've checked on https://pf4.patternfly.org/components/checkbox/#with-description and copy-pasting the example checkbox several times gives the same result 🤷
> So, I think it's a Patternfly thing... I guess we shouldn't fix it with custom CSS, so... that's fine.

Patternfly doesn't really have a "checkboxes input" like Formtastic, so IMO we can just add the spacing manually (check updated screenshot).

I also updated the empty state.

**Review by mayorova — APPROVED** [review]
Looks great! Thanks @josemigallas

**Pull request merged**
