### PR TITLE
Adding pristinejs to validate forms

### PR DESCRIPTION
**Pull request by damianpm**
**What this PR does / why we need it**:

Adds form validation to PF4/React forms

**Which issue(s) this PR fixes** 

https://issues.jboss.org/browse/THREESCALE-2993

**Special notes for your reviewer**:

We are using [PF4 react form](https://patternfly-react.surge.sh/patternfly-4/components/form/) elements. PF doesn't provide any kind of validation, it only expects you to pass a boolean prop to the input fields and an error message to show the corresponding styles.

We should choose a validation library (or craft our own). I've been testing some libraries and I think we could use [Pristine](https://github.com/sha256/Pristine).

**Pros:**
- Small (~4kb minified)
- No additional dependencies
- Non-intrusive (It can only return a simple boolean, or an errors object. It has an option to add styled -error messages, but it's totally optional)
- Active project (last commit  4 Mar, 2019)

**Cons:**
- Early development stage (`"pristinejs": "^0.1.6"`)
- No license (is that an issue?)
- Only 2 contributors

### CODE REVIEW

**Comment by thomasmaas** [comment]
@damianpm can you motivate why this library is the right choice? (pf4 (react) doesn't come with any validations out of the box or preferred library to use?)

**Comment by thomasmaas** [comment]
I'd say no license is an issue, any opinions @didierofrivia ?

**Comment by didierofrivia** [comment]
@thomasmaas There's always a license, check the repo, website, etc..

**Comment by damianpm** [comment]
> @thomasmaas There's always a license, check the repo, website, etc..

Well, in this repo I couldn't find the license.
Anyway I'm testing another library

**Comment by didierofrivia** [comment]
@damianpm @thomasmaas https://github.com/sha256/Pristine/blob/master/package.json#L22

**Comment by damianpm** [comment]
Closing in favor of https://github.com/3scale/porta/pull/1005

**Pull request closed without merging**
