### PR TITLE
Remove recommended Ruby VM from .ruby-version

### PR DESCRIPTION
**Pull request by guicassolato**
**What this PR does / why we need it**:

This PR transfers recommended Ruby VM to ~the bundle file (Gemfile) and removes .ruby-version from the code base. It more or less reverts https://github.com/3scale/porta/pull/399~ a sample file.

**Which issue(s) this PR fixes** 

https://github.com/3scale/porta/pull/828 broke dev setups using rbenv. As stated by rbenv's team, they want "to ensure a consistent environment across development and production" and therefore do not intend to support abbreviated ruby version in .ruby-version file. See https://github.com/rbenv/rbenv/issues/328.

### CODE REVIEW

**Comment by thomasmaas** [comment]
@guicassolato Wouldn't it be more correct to state that https://github.com/3scale/porta/pull/828 broke dev settings as that pr introduces abbreviated ruby version.

**Comment by hallelujah** [comment]
This will make nightly builds fail :/
We have nightly on 2.4 with mysql + postgres + oracle

**Comment by guicassolato** [comment]
> @guicassolato Wouldn't it be more correct to state that #828 broke dev settings as that pr introduces abbreviated ruby version.

Sorry, @thomasmaas : i had pasted the wrong link. Fixed in the description.

**Comment by guicassolato** [comment]
> This will make nightly builds fail :/
> We have nightly on 2.4 with mysql + postgres + oracle

I know, @hallelujah. That was intentional. I will get a screenshot of the failure for the record and fix the PR to ruby version 2.4.

**Comment by guicassolato** [comment]
Oh! It's always good to be wrong... I was expecting the build in OpenShift to fail due to ruby 2.4 in the base of the Dockerfile while 2.3 dependency is stated in the Gemfile, but it turns out it does NOT fail.

Screen Shot 2019-06-03 at 12 18 37 PM

**Comment by guicassolato** [comment]
@hallelujah reminded me of an also interesting to consider alternative, having a `.ruby-version.sample` file. Example: https://github.com/discourse/discourse/blob/master/.ruby-version.sample.

Thanks, @hallelujah .

**Pull request merged**
