### PR TITLE
sometimes search indexing becomes broken

### PR DESCRIPTION
**Pull request by akostadinov**
This is just an experimental fix but we need to get it in master to have a proper alpha build. Otherwise can't reproduce this intermittent problem.

Upstream information about the issue pat/thinking-sphinx#1219

Also need to figure out whether we need both exception types.

### CODE REVIEW

**Comment by mayorova** [comment]
I'm having a hard time understanding the reason of this error, and why reestablishing the connection would fix it.
But let's give it a try :wink:

**Review by mayorova — APPROVED** [review]

**Review by jlledom — DISMISSED** [review]
I don't really like the idea. First, we're filtering the exceptions by message:

`exception.message.include?("unknown column")`

I think that will match false positives, probably even filtering by error class would.

Also, this is a workaround. The solution  is probably updating Sphinx or migrating to Manticore. As Sphinx is abandoned.

Anyway, I know this is only for testing so I'm approving. But what's your idea to solve this in the long term?

**Comment by mayorova** [comment]
@jlledom I guess this is just to prevent QE tests from failing.
I think the long-term solution would be to upgrade to Manticore, and hope that it will be fixed there at some point :crossed_fingers:  :sweat_smile:

**Comment by akostadinov** [comment]
Also it's not only about tests. This can possibly happen in a real-world deployment. At least I assume so.

**Comment by jlledom** [comment]
It seems we don't have many options. Sphinx 2.2.1 is badly outdated. Sphinx 3 is not abandoned as I though, but it's not open source. And we aren't sure Manticore would fix the bug, to be worth the effort to upgrade. So I guess this is the best we can do now.

**Review by jlledom — APPROVED** [review]

**Pull request merged**
