### PR TITLE
⚰️ Remove multi-part form support

### PR DESCRIPTION
**Pull request by josemigallas**
🧹🧹🧹 

Remove function `ajaxUpload` which is used nowhere.

(part of https://issues.redhat.com/browse/THREESCALE-10943)

### CODE REVIEW

**Review by jlledom — DISMISSED** [review]
I'm all for removing code but I don't know what were these files for. Could you please explain why are they not needed anymore?

**Comment by josemigallas** [comment]
> I'm all for removing code but I don't know what were these files for. Could you please explain why are they not needed anymore?

Unfortunately not. The file `application.js` is all duplicated code from 3scale and 3scale_v2, but I think it still used (tests are failing). On the other hand the multi-part forms thing was added 14 year ago and nowadays there are no references to it, so I assume we don't care about it.

The issue with this "forgotten" features is that they carry old libraries that create a lot of tech debt. Even if we need it again in the future (unlikely) I think we are better off if we re-write using modern libraries.

**Comment by mayorova** [comment]
Apparently this is still used in some modals (fancyboxes?) 

https://github.com/3scale/porta/blob/386005cf6006e20f670a0cd3da8c25224384ef46/app/assets/javascripts/application.js#L184-L192

E.g. in plan features edit form:

Screenshot from 2024-04-09 14-24-20

or the application keys update form
Screenshot from 2024-04-09 14-44-39

**Comment by josemigallas** [comment]
@mayorova @jlledom I reverted the application.js part, this is only about multipart forms now.

**Review by mayorova — APPROVED** [review]

**Review by jlledom — COMMENTED** [review]
If you don't remove `application.js`, then you can't remove the `ajaxUpload()` function because it's being called from there:

https://github.com/3scale/porta/blob/c4d6a8e3985e128796fc23b01050c7838b3fedba/app/assets/javascripts/application.js#L10

It's ok to remove the duplicates, though.

**Comment by josemigallas** [comment]
> If you don't remove `application.js`, then you can't remove the `ajaxUpload()` function because it's being called from there:
> https://github.com/3scale/porta/blob/c4d6a8e3985e128796fc23b01050c7838b3fedba/app/assets/javascripts/application.js#L10
> It's ok to remove the duplicates, though.

The method is called on a selector that does not exist. It was used 15 years ago to upload files via ajax but this AFAIK is not used anymore.

**Review by jlledom — APPROVED** [review]

**Pull request merged**
