### PR TITLE
Removes services from the ApiSelector (aka ContextSwitcher)

### PR DESCRIPTION
**Pull request by josemigallas**
**What this PR does / why we need it**:

As part of the improvements in the Dashboard, we're removing the list of services and searchbar inside the ContextSwitcher.

Screenshot 2020-10-08 at 16 57 51

Screenshot 2020-10-08 at 16 58 03

**Which issue(s) this PR fixes** 

[Address UI scalability issues in API Management Service](https://issues.redhat.com/browse/APPDUX-462)

### CODE REVIEW

**Review by Martouta — APPROVED** [review]
Thanks!! 👏

**Review by Martouta — DISMISSED** [review]

**Review by thomasmaas — APPROVED** [review]
Now that we have a much shorter list we can also reconsider including account settings at the bottom of the list.

**Review by Martouta — APPROVED** [review]

**Review by dlabaj — APPROVED** [review]
LGTM

**Review by christiemolloy — APPROVED** [review]
LGTM!!!

**Review by Martouta — APPROVED** [review]

**Pull request merged**
