### PR TITLE
Remove unused old endpoint /master/api/domain/:id

### PR DESCRIPTION
**Pull request by Martouta**
It used to be called from https://github.com/3scale/wildcard-router-service until 2.5 or 2.6 but that repo is not used anymore and now Zync is used instead for that purpose and it does not use that endpoint but a completely different approach.

Removing this simplifies a lot the optimization of proxy config endpoints. Besides, this piece of code had a bug for oracle and postgres: https://github.com/3scale/porta/pull/2256#discussion_r525084068

### CODE REVIEW

**Review by josemigallas — APPROVED** [review]

**Review by macejmic — APPROVED** [review]

**Review by guicassolato — APPROVED** [review]
Really hard to tell if some one is using this. Ideally, we would first deprecate the endpoint, then remove it. However, I think it's safe to remove it given:
1. the urgency of this to move on with other stuff;
2. the fact the endpoint is restricted to master domain and master user access tokens;
3. that we know this endpoint was [introduced in 2018](https://github.com/3scale/system/pull/8903) so the wildcard-router could have info about domains;
4. we couldn't find any other clear dependency on this endpoint (neither in porta, nor in https://github.com/3scale/APIcast).

**Comment by Martouta** [comment]
5. the endpoint is not documented anywhere 😄 (that on its own isn't big but added to all of the previous reasons then it is a thing)

**Comment by Martouta** [comment]
Merging.
@thomasmaas @didierofrivia if you disagree, we can revert 👍🏼

**Comment by didierofrivia** [comment]
It was pretty much safe to remove, if we start receiving issues from support, we could always revert. Good work!

**Pull request merged**
