### PR TITLE
🦋 Render Policy Edit and New inside a modal

### PR DESCRIPTION
**Pull request by josemigallas**
[THREESCALE-10042: Apply Patternfly to Policies](https://issues.redhat.com/browse/THREESCALE-10042)

Before:
Screenshot 2023-08-16 at 12 15 10
Screenshot 2023-08-16 at 12 15 13
Screenshot 2023-08-16 at 12 15 17

After:
Screenshot 2023-08-16 at 12 11 44
Screenshot 2023-08-16 at 12 11 54
Screenshot 2023-08-16 at 12 11 49

### CODE REVIEW

**Comment by jlledom** [comment]
I tried importing 70kb of policies and the popup took about a second to open, it's slow but we don't expect people to manually insert that amount of policies from the UI.

I found that the `Update Policy` button doesn't work. It shows this error in the console: `Uncaught TypeError: document.forms.namedItem(...) is null`

**Review by mayorova — CHANGES_REQUESTED** [review]
As @jlledom pointed out Update Policy button does not work, to me it throws:
```
EditPolicyModal.tsx:42 Uncaught TypeError: Cannot read properties of null (reading 'requestSubmit')
    at onClick (EditPolicyModal.tsx:42:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3555:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3599:1)
    at invokeGuardedCallback (react-dom.development.js:3654:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:3668:1)
    at executeDispatch (react-dom.development.js:7290:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:7316:1)
    at processDispatchQueue (react-dom.development.js:7327:1)
    at dispatchEventsForPlugins (react-dom.development.js:7336:1)
    at react-dom.development.js:7514:1
```

Also, there is a warning in the console (not sure if it's related):

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Form
```

**Review by lvillen — DISMISSED** [review]
It is working as expected for me, I didn't have that problem @jlledom and @mayorova mentioned. It worths looking into it but approved on my side.

**Comment by josemigallas** [comment]
> Also, there is a warning in the console (not sure if it's related):
> 
> ```
> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: Form
> ```

This comes from `react-jsonschema-form` and we can ignore it for now...

**Review by lvillen — DISMISSED** [review]

**Comment by mayorova** [comment]
> After: Screenshot 2023-08-16 at 12 11 54 

The `+` button looks a bit weird - is it intentionally that wide? And the color is different.

As a potential improvement - the `Update Policy` button could be disabled when no changes are made to the policy configuration. But well, that's not a must if it's not easy.

**Comment by josemigallas** [comment]
> The `+` button looks a bit weird - is it intentionally that wide? And the color is different.
> 
> As a potential improvement - the `Update Policy` button could be disabled when no changes are made to the policy configuration. But well, that's not a must if it's not easy.

I managed to maintain all styles... I think. Maybe something else broke but I haven't seen anything
Screenshot 2023-09-15 at 12 20 06
Screenshot 2023-09-15 at 13 00 34

**Review by mayorova — APPROVED** [review]

**Pull request merged**
