### PR TITLE
🧑‍💻 Remove annoying `webpack-dev-server` overlay

### PR DESCRIPTION
**Pull request by josemigallas**
Just for development

### CODE REVIEW

**Comment by mayorova** [comment]
What's this overlay? :sweat_smile:

**Comment by josemigallas** [comment]
> What's this overlay? 😅

>[**devServer.overlay**](https://v4.webpack.js.org/configuration/dev-server/#devserveroverlay)
Shows a full-screen overlay in the browser when there are compiler errors or warnings. If you want to show only compiler errors:

**Review by lvillen — APPROVED** [review]

**Comment by akostadinov** [comment]
don't we want to follow these styles? I guess not, given you remove it...
If you're sure in what you're doing..

**Comment by josemigallas** [comment]
> don't we want to follow these styles? I guess not, given you remove it... If you're sure in what you're doing..

We're not removing the linter or the styles, just the annoying overlay that honestly drives me mad every time I am trying stuff. I am sure @lvillen can relate.

**Comment by akostadinov** [comment]
Makes sense.

**Pull request merged**
