### PR TITLE
[WIP] [Rails 5] I18n.t('date.formats.long') output has changed

### PR DESCRIPTION
**Pull request by Martouta**
Extracted from https://github.com/3scale/porta/pull/4/commits/66bc5ef3a1a1208c67ab53f0ce16e718d4c72730

### CODE REVIEW

**Comment by hallelujah** [comment]
There is a strange issue with the `:long` format of Date
```ruby
# On rails 4.2
m = Month.new Time.now
#=> Wed, 01 Jan 2020..Fri, 31 Jan 2020
m.to_s
#=> "January  1, 2020 - January 31, 2020"

# on rails 5.0
 m = Month.new Time.now
#=> Wed, 01 Jan 2020..Fri, 31 Jan 2020
m.to_s
#=> "January 01, 2020 - January 31, 2020"
```

I think because or some gem rails changes how time "%d" should be displayed

**Comment by hallelujah** [comment]
I remember:

```
#### rails 4

```ruby
Date::DATE_FORMATS[:long]
#=> "%B %e, %Y"
```

#### rails 5

```ruby
Date::DATE_FORMATS[:long]
#=> "%B %d, %Y"
```

**Comment by Martouta** [comment]
@hallelujah And I guess it is also related to [THREESCALE-4363](https://issues.redhat.com/browse/THREESCALE-4363)

**Comment by Martouta** [comment]
[only-rails5]

**Pull request closed without merging**
