### PR TITLE
[2.4 feature] Keep 'application' and its 'analytics' inside Service context

### PR DESCRIPTION
**Pull request by Martouta**
Fixes point 4. of [THREESCALE-1321](https://issues.jboss.org/browse/THREESCALE-1321)

- [X] Application show page under Service scope
image
- [X] Application edit page under Service scope
image
- [X] Application Analytics page under Service scope
image
- [X] Fix and add tests.

### CODE REVIEW

**Comment by thomasmaas** [comment]
when trying to save an app without a name: `translation missing: en.buyers.applications.edit.delete_confirmation` `msg = t('.delete_confirmation', name: h(application.name))`

**Comment by Martouta** [comment]
@thomasmaas I know, it is one of the bugs I am currently fixing 😄 👍

**Comment by thomasmaas** [comment]
ok, something out of scope: would be nice to have new application functionality in apps index of each service. but we can do that later

**Comment by Martouta** [comment]
@thomasmaas I've just made its own Jira issue for that new task [THREESCALE-1336](https://issues.jboss.org/browse/THREESCALE-1336) 😉

**Comment by Martouta** [comment]
I need reviews from @thomasmaas and from someone from Rails (@guicassolato, @macejmic or @hallelujah when he is already fine, but better not to wait until that knowing he will have many things to do)

**Pull request merged**
