### PR TITLE
THREESCALE-1471 Fix Aligning list items using flex

### PR DESCRIPTION
**Pull request by damianpm**
**What this PR does / why we need it**:

FIX Master - Aligning list items using flex

### CODE REVIEW

**Comment by thomasmaas** [comment]
@damianpm would be good to merge this asap.

**Comment by damianpm** [comment]
> @damianpm would be good to merge this asap.

I'm testing on IE, almost pushing

**Comment by damianpm** [comment]
@thomasmaas @josemigallas 
PR Updated:

-----
**CHROME:**

**Single line:**

chrome-lg
-----
**Multiline:**
chrome-sm

-----
**IE 11:**

**Single line:**

ie-lg
-----
**Multiline:**
ie-sm

**Note:** Is not possible to align list items to the right. It's possible in Firefox/Chrome, but not in IE11.

**Comment by thomasmaas** [comment]
@damianpm but they are left aligned in chrome screenshots?

**Pull request merged**
