### PR TITLE
THREESCALE-8115 added autocomplete off

### PR DESCRIPTION
**Pull request by nidhi-soni1104**
What this PR does / why we need it:

Autocomplete attribute is set to "on" for the credentials fields in the login page

Which issue(s) this PR fixes

https://issues.redhat.com/browse/THREESCALE-8115

### CODE REVIEW

**Comment by nidhi-soni1104** [comment]
> https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields
> 
> _Even without a master password, in-browser password management is generally seen as a net gain for security. Since users do not have to remember passwords that the browser stores for them, they are able to choose stronger passwords than they would otherwise._
> 
> _For this reason, many modern browsers do not support autocomplete="off" for login fields._
> 
> Seems to me the jira issue is incorrect.
Then need to find alternate if we can but generally we cant mess up with browser setting related things

**Comment by secretsurf** [comment]
I don't think this code is wrong though. It will work on browsers that support it and that's all we can do. I would merge this. What do you think, @thomasmaas?

**Comment by nidhi-soni1104** [comment]
Closing this PR for now

**Comment by nidhi-soni1104** [comment]
@thomasmaas @secretsurf Can we merge this?

**Comment by nidhi-soni1104** [comment]
As per the comment mentioned by cat in Jira I am merging this PR and closing JIRA as well

**Pull request merged**
