### PR TITLE
[gem] Fixing Gemfile.lock for on-premises

### PR DESCRIPTION
**Pull request by hallelujah**
This will also fix nightly builds

### CODE REVIEW

**Comment by hallelujah** [comment]
Agree. I was thinking the same

**Comment by gsaslis** [comment]
yes, this should be checked in the bundler dependencies job?

looks like that `--deployment` there is the root cause for this not showing up earlier, right?

**Comment by hallelujah** [comment]
@gsaslis no we need to leave `--deployment` there
Basically the CI would add a job:

```
BUNDLE_GEMFILE=Gemfile bundle install --deployment --retry=5 --bundle-without development:test

BUNDLE_GEMFILE=Gemfile.on_prem bundle install --deployment --retry=5 --bundle-without development:test
```

**Comment by mikz** [comment]
@hallelujah except the second would not pass on forks, because it needs credentials, so it can't be required step of the CI.

**Comment by hallelujah** [comment]
You're right the first should not be done there

**Comment by gsaslis** [comment]
> BUNDLE_GEMFILE=Gemfile bundle install --deployment --retry=5 --bundle-without development:test

hmmm but if we exclude test dependencies, as I think you're suggesting, how do we then expect tests to pass? 

I am assuming tests rely on some of the gems in `test` group, no?

shouldn't we be going for: 

`BUNDLE_GEMFILE=Gemfile bundle install --deployment --retry=5 --bundle-without development`
?

**Comment by hallelujah** [comment]
OK lets merge #44 and we will talk about that job. It will be clearer what we would need to do

**Comment by gsaslis** [comment]
ok, so now that #44 has indeed been merged ( 🎉 ), i guess we can move forward with this. 

so, @hallelujah do you think `test` gems group should also be excluded?

**Comment by hallelujah** [comment]
It looks like fixed in current master. Closing

**Pull request closed without merging**
