### PR TITLE
[oracle] Fix invoice procedure for friendly_id

### PR DESCRIPTION
**Pull request by hallelujah**
Relates to https://github.com/3scale/porta/pull/64
Fixes https://github.com/3scale/porta/issues/82

* Use of cursor_sharing: exact for development and CI
* Use of a custom private oracle based on https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance putting 4096 to [12.2.0.1/dbca.rsp.tmpl](https://github.com/oracle/docker-images/blob/55112ee34872110be3c0f662188be7a30a9866fc/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1/dbca.rsp.tmpl#L204)
* Also refactors system/dataabase library

### CODE REVIEW

**Comment by Martouta** [comment]
imo we should add the `oracle` label to run the tests even if we have other issues there. It won't pass but we will know if at least it is better or not 😄

**Comment by Martouta** [comment]
Not that bad then 😄This fixed a lot!
It is only failing in these 2:
image
and:
image

**Comment by gsaslis** [comment]
this `1 / Applications management.Delete application events` fails SO often...

**Comment by Martouta** [comment]
@gsaslis Well, it is not the famous `Net::ReadTimeout` 😂 But this one also may happen from time to time 😂

**Comment by gsaslis** [comment]
:D 

@Martouta should we add this to the list on #22 ?

**Comment by Martouta** [comment]
i don't know yet @gsaslis 👍

**Comment by hallelujah** [comment]
Oracle green https://jenkins-aws.3sca.net/job/system-upstream/job/pipeline-oracle/56/

**Comment by hallelujah** [comment]
screen shot 2018-10-05 at 17 51 51
Green :)

**Pull request merged**
