### PR TITLE
Usage rules fix

### PR DESCRIPTION
**Pull request by avilatusell**
**What this PR does / why we need it**:
This PR is a follow up of [#2238 ](https://github.com/3scale/porta/pull/2238) that includes the suggested changes from [#2238 ](https://github.com/3scale/porta/pull/2238). 
Refer to original issues for complete description of current behaviour.

**Which issue(s) this PR fixes** 
Fixes [THREESCALE-6295](https://issues.redhat.com/browse/THREESCALE-6295) and [THREESCALE-6296](https://issues.redhat.com/browse/THREESCALE-6296).

**Verification steps** 
Please refer to [#2238 ](https://github.com/3scale/porta/pull/2238).

**Notes**:
There are no UI tests included. If we should include them @3scale/system-ux could you please let us know where we should write the tests? Thanks.

### CODE REVIEW

**Comment by josemigallas** [comment]
@avilatusell I added the minimal tests for your PR to this branch https://github.com/3scale/porta/tree/THREESCALE-6295-6296-usage-rules-fix_tests. Feel free to use them!

**Comment by kevprice83** [comment]
Thanks for that @josemigallas ! Interesting so these feature steps definitions are tests for UX related features? i.e. frontend. Would documentation such as [this](https://cucumber.io/docs/tools/ruby/) be everything we need to refer to to be able to understand how to write cucumbers? To run a cucumber in porta can we simply run this [rake task](https://github.com/3scale/porta/blob/3017562449d3275840cae6afe338a01c1dcca899/lib/tasks/cucumber.rake)? Or is there a better way to run just the cucumber that we are writing? I guess these are run as part of the [circleci build](https://github.com/3scale/porta/blob/f62a42108f7828069c608f5d9037fb66111b5725/.circleci/config.yml#L232-L254) right?

**Comment by hallelujah** [comment]
@kevprice83 Cucumber are not for frontend testing. It is more for business understanding/specification.
We do it wrong but we will correct that.

To do front end testing, capybara and ruby or any JS test (if JS is heavily involved) just work

**Review by hallelujah — APPROVED** [review]

**Comment by hallelujah** [comment]
Commits are not signed but OK.
@avilatusell next time please follow https://github.com/3scale/porta/blob/master/CONTRIBUTING.md#is-there-any-other-requirement-to-open-a-pr

**Pull request merged**
