### PR TITLE
Upgrade Sidekiq to 5.2.7

### PR DESCRIPTION
**Pull request by duduribeiro**
**What this PR does / why we need it**:

This commit upgrades our version of Sidekiq. Version 5x includes
a better support for code reloading in development.

**Special notes for your reviewer**:

Sidekiq changed the default concurrency from 25 to 10 (https://github.com/mperham/sidekiq/issues/3892). I don't know if this will affect something in our app.

### CODE REVIEW

**Comment by Martouta** [comment]
> Sidekiq changed the default concurrency from 25 to 10

For sure that affects us. I don't know all the implications that it has, but this is one of them:
https://github.com/3scale/porta/blob/8aed1303c2193d09b788696c4159c8cb9032770b/app/workers/zync_worker.rb#L16-L23

This code is relying on being retried up to 25 times, and it changes the retry time to don't be longer than a week in total because otherwise the event is gone.

**Comment by duduribeiro** [comment]
> > Sidekiq changed the default concurrency from 25 to 10
> 
> For sure that affects us. I don't know all the implications that it has, but this is one of them:
> https://github.com/3scale/porta/blob/8aed1303c2193d09b788696c4159c8cb9032770b/app/workers/zync_worker.rb#L16-L23
> 
> This code is relying on being retried up to 25 times, and it changes the retry time to don't be longer than a week in total because otherwise the event is gone.

@Martouta  in this case we should close this PR ou merge it and rely on the servers to run sidekiq with `-c 25` 😄

**Comment by duduribeiro** [comment]
> > > Sidekiq changed the default concurrency from 25 to 10
> > 
> > 
> > For sure that affects us. I don't know all the implications that it has, but this is one of them:
> > https://github.com/3scale/porta/blob/8aed1303c2193d09b788696c4159c8cb9032770b/app/workers/zync_worker.rb#L16-L23
> > 
> > This code is relying on being retried up to 25 times, and it changes the retry time to don't be longer than a week in total because otherwise the event is gone.
> 
> @Martouta in this case we should close this PR ou merge it and rely on the servers to run sidekiq with `-c 25` 😄

@Martouta about the snippet that you send: it is from retries. I think concurrency should not interfere on it AFAIK

**Comment by Martouta** [comment]
hahahahahahah i read it wrong, sorry 🤦‍♀ 🙈 😊 😂

**Comment by hallelujah** [comment]
Closing in favor of #1703

**Pull request closed without merging**
