### PR TITLE
🥒 Remove `@javascript` tag

### PR DESCRIPTION
**Pull request by josemigallas**

### CODE REVIEW

**Review by akostadinov — APPROVED** [review]
If you are sure that these tests remain valid without `@javascript` better without it.

**Comment by josemigallas** [comment]
> If you are sure that these tests remain valid without `@javascript` better without it.

I think if these tests really rely on`@javscript`, they should fail without it. However maybe @jlledom can clarify the reason behind it.

**Comment by jlledom** [comment]
> > If you are sure that these tests remain valid without `@javascript` better without it.
> 
> I think if these tests really rely on`@javscript`, they should fail without it. However maybe @jlledom can clarify the reason behind it.

It was this commit: https://github.com/3scale/porta/commit/c8d9825dbda1fcb11051b78d3c02caba131a891f#diff-79bdf601d34b1da4ffa3296d9def6b62c8291c18147f56b668535d76a1acfea6

@javascript was included at the first line, for all tests, but I wanted to add a test without javascript, so I manually added the @javascript tag to all tests except mine.

**Review by jlledom — APPROVED** [review]
If the tests are still valid without @javascript, I approve.

**Pull request merged**
