### PR TITLE
Replace context selector classes with Patternfly equivalents

### PR DESCRIPTION
**Pull request by damianpm**
**What this PR does / why we need it**:

Fixing broken tests for https://github.com/3scale/porta/pull/2365

### CODE REVIEW

**Comment by srambach** [comment]
From my standpoint, the context selector looks and behaves correctly. 👍

**Comment by damianpm** [comment]
@srambach @cntlsn @josemigallas 

Applying PF styles changes a bit the context selector, is that expected?

**Before:**
before

**After:**
after

**Comment by srambach** [comment]
> @srambach @cntlsn @josemigallas
> 
> Applying PF styles changes a bit the context selector, is that expected?
> 
Yes, that was expected, does it look correct @cntlsn ?

**Review by cntlsn — APPROVED** [review]
LGTM!

**Pull request merged**
