### PR TITLE
[doc] Install chromedriver on Mac OS X

### PR DESCRIPTION
**Pull request by hallelujah**
Complete the installation instructions by installing the chromedriver for tests

### CODE REVIEW

**Comment by gsaslis** [comment]
does this mean we are abandoning the Brewfile approach in https://github.com/3scale/porta/pull/510 ?

**Comment by didierofrivia** [comment]
I agree with @gsaslis , would be good to keep the Brewfile aproach (in the making)

**Comment by josemigallas** [comment]
@gsaslis @didierofrivia This is just adding a step to install chromedriver, it does not replace any other approach (I think?)

**Comment by didierofrivia** [comment]
@josemigallas then it will be necessary to remove this when https://github.com/3scale/porta/pull/510 is merged, in order to avoid redundancy

**Comment by Martouta** [comment]
@didierofrivia @josemigallas As I said in https://github.com/3scale/porta/pull/510#issuecomment-453968974, that PR implies updating almost all our current `INSTALL.md` already and that's fine 👍:smile:

**Pull request merged**
