### PR TITLE
[WIP] Validate that for a BackendApiConfig, its Service and BackendAPI belong to the same tenant

### PR DESCRIPTION
**Pull request by Martouta**
Without this validation, we can have big problems :stuck_out_tongue_closed_eyes:

### CODE REVIEW

**Comment by hallelujah** [comment]
We have the tenant_id triggers already

So it should not be an issue, and if it is then all our models need this check

**Comment by Martouta** [comment]
> We have the tenant_id triggers already
> So it should not be an issue

In the trigger we are putting the same tenant_id as the backend_api:
https://github.com/3scale/porta/blob/d76fdf8e0bab92a31cfe3ae2021fa78b42380d49/lib/system/database/definitions/mysql.rb#L452-L456

That does not mean that the backend_api and the service belong to the same tenant

> then all our models need this check

Give me an example then of a model in this situation :stuck_out_tongue_closed_eyes: And if we need it, we do anyway :woman_shrugging: In this case the backend_api_config belongs both to a backend_api and to a service, and somehow in the controllers we are going to allow the id of one of them, and that means that if the customers are allowed to set an id of an existing object that does not belong to them, we are in trouble...
For the API in particular I am searching the object inside the scope of the current_account or it returns 404, and I dunno if @guicassolato is checking that in the controller of the UI (imo he should), but still I am not sure if it is safer to also have this check in the model :thinking:

**Comment by Martouta** [comment]
I added [this comment](https://github.com/3scale/porta/pull/1230#discussion_r327504663) for this problem in the review of the UI.

**Comment by hallelujah** [comment]
In the other case we should just load the BackendApi with `current_account.backend_appi.find(params[:backend_api_id])` and done

**Comment by Martouta** [comment]
Right :+1: Conclusion:
image

**Pull request closed without merging**
