### PR TITLE
🦋 Update Service Contracts index table

### PR DESCRIPTION
**Pull request by josemigallas**
[THREESCALE-9868: Accounts > Service subscriptions](https://issues.redhat.com/browse/THREESCALE-9868)

### Before:
Screenshot 2024-07-17 at 14 03 21

Screenshot 2024-07-17 at 14 03 28

Screenshot 2024-07-17 at 17 08 34

Screenshot 2024-07-17 at 17 27 24

### After:

Screenshot 2024-07-17 at 14 03 54

Screenshot 2024-07-17 at 14 03 44

Screenshot 2024-07-17 at 17 45 01

Screenshot 2024-07-17 at 17 45 10

### CODE REVIEW

**Review by jlledom — COMMENTED** [review]
A few comments:

1. On Firefox, the `Change service plan` modal shows an annoying scroll bar that overlaps the submit button. This already happens in master, but I think this is a good opportunity to fix it.

Screenshot from 2024-07-17 10-48-59

2. The new cucumber suite for the index screen has several scenarios to test filtering, but I can't find how to filter values in the actual screen:

image

Am I missing something?

Everithing else LGTM.

**Comment by josemigallas** [comment]
> A few comments:
> 1. On Firefox, the `Change service plan` modal shows an annoying scroll bar that overlaps the submit button. This already happens in master, but I think this is a good opportunity to fix it.

Well that is actually happening everywhere and I'm not sure this is the place to fix it, but I will take a look at it just in case.

> 2. The new cucumber suite for the index screen has several scenarios to test filtering, but I can't find how to filter values in the actual screen:
> 
> [image]
> Am I missing something?

Yes, those cucumbers don't belong to that screen 😄. In master the buyer's service subscriptions tab do not allow filtering unlike the provider's one (see the screenshots I added to the description). However, I don't think this makes sense... so I will add the same toolbar (and also create cucumbers for _that_ page).

**Comment by jlledom** [comment]
> Well that is actually happening everywhere and I'm not sure this is the place to fix it, but I will take a look at it just in case.

OK, if it happens everywhere maybe fix it in another PR.

> > Am I missing something?
> 
> Yes, those cucumbers don't belong to that screen 😄. 

Oh, that would explain it... 🤦🏼‍♂️

> In master the buyer's service subscriptions tab do not allow filtering unlike the provider's one (see the screenshots I added to the description).

I was on the admin portal, not master portal. To see the screen that contains the filters you need to enable service subscriptions from  "Accounts > Settings > Usage Rules"

> However, I don't think this makes sense... so I will add the same toolbar (and also create cucumbers for that page).

That'd be better because it's confusing to have a `Clear all filters` button when there's no results and not having any filter available in the screen.

**Review by jlledom — DISMISSED** [review]
I checked out the last changes and it works fine for me 👍

**Pull request merged**
