### PR TITLE
⬆️ Upgrade `jquery-ui` to 1.13.2 in CMS

### PR DESCRIPTION
**Pull request by josemigallas**
Part 2 of 2.
Based on #3698 

[THREESCALE-7954: Upgrade jquery-ui to 1.13 in admin portal](https://issues.redhat.com/browse/THREESCALE-7954)

### CODE REVIEW

**Review by jlledom — COMMENTED** [review]
Is there something I can test in order to verify this works locally?

**Comment by josemigallas** [comment]
> Is there something I can test in order to verify this works locally?

In general verify the CMS works as expected. It uses 3 widgets:
* Draggable & Droppable: it allows dragging items within the sidebar. My guess is you can move a file from one folder into another but it does not work like that. I think it works like that in master.
* Tabs: 2 tabs in the main page "Quick Links" and "Snippets" and 2 other tabs in the edit pages "Draft" and "Published".

**Comment by jlledom** [comment]
>     * Draggable & Droppable: it allows dragging items within the sidebar. My guess is you can move a file from one folder into another but it does not work like that. I think it works like that in master.

Drag & drop from the left bar to the section content panel works fine. I can't move a file across folders, neither in production, how do you do this?

>     * Tabs: 2 tabs in the main page "Quick Links" and "Snippets" and 2 other tabs in the edit pages "Draft" and "Published".

This works fine.

It seems to work fine for me, but test fail.

**Review by jlledom — APPROVED** [review]
Tests pass. 👍

**Comment by josemigallas** [comment]
> > ```
> > * Draggable & Droppable: it allows dragging items within the sidebar. My guess is you can move a file from one folder into another but it does not work like that. I think it works like that in master.
> > ```
> 
> Drag & drop from the left bar to the section content panel works fine. I can't move a file across folders, neither in production, how do you do this?

I doubt it works in production... it seems to me like a very old functionality that nobody uses anymore and it must've broken at some point. In case it's still functional, there are no breaking changes in the new jquery-ui version so there's little chance if any that it's broken now.

**Pull request merged**
