### PR TITLE
Update MySQL to 8.0 in CircleCI

### PR DESCRIPTION
**Pull request by mayorova**
3scale on-premises already supports MySQL 8.0, and we're going to migrate SaaS soon also.

### CODE REVIEW

**Review by jlledom — APPROVED** [review]

**Review by akostadinov — APPROVED** [review]

**Comment by akostadinov** [comment]
`features/provider/admin/account/email_configurations.feature:13` seems to be a real issue. On a first glance pPerhaps MySQL 8 became smarter with ordering numbers. So I think we should just update the test to check for the new behavior.

**Comment by mayorova** [comment]
So, the reason is that `updated_at` field (by which the email configurations are ordered by default) has second precision. All of the test data are very likely to be created within the same second, so I guess in MySQL the order in this case is unpredictable, really (as I guess is expected).

Probably, MySQL 5.7 used some kind of optimization that returned the entries in the same order always (maybe based on the actual entry insertion timestamp, or the ID, who knows...).

Anyway, while it seems that we shouldn't be relying on this `updated_at` field too much, I think we don't actually care that much if the order is different on page reloads.

So, IMO fixing the test is enough to go forward.

**Comment by akostadinov** [comment]
Probably UI should present order based on primary key instead of `updated_at`. After all `id` will be higher for objects created later. Fixing the test would be messy.

Also not sure we should order by last created. But somebody decided so. idk

**Comment by mayorova** [comment]
Fixing the test was actually simple.
Although it's funny that now in CircleCI where the **MySQL** version has changed, only PostgreSQL and Oracle builds fail :sweat_smile: (for reasons unrelated with the test fix)

> Probably UI should present order based on primary key instead of updated_at. After all id will be higher for objects created later. Fixing the test would be messy (I mean to me it looks "not right").

This actually makes sense. I think I'll apply the suggestion.

> Also not sure we should order by last created. But somebody decided so. idk

Well, given that this feature is used uniquely by us (admins of SaaS), I think we can re-decide :)
Definitely order is not something that anyone using this UI would care about.

**Review by akostadinov — APPROVED** [review]

**Comment by akostadinov** [comment]
Looks nice, although looking at it now, it is not sorting by `updated_at`. We may update a configuration and despite it having an older `id` it will have a later `updated_at`. My simple suggestion made a little mess...

**Comment by mayorova** [comment]
@akostadinov By default, when the page is open, the list is sorted by ID, but the option of sorting by `updated_at` is still there, lists can be ordered in ASC or DESC mode.

Ideally, in such case it probably would make sense to sort by two fields: first the timestamp, and then the ID (just to avoid randomness of the result).

But it's not worth for the Email Configurations, really...

**Comment by akostadinov** [comment]
Works for me.

**Comment by jlledom** [comment]
I updated the mysql image in `docker-compose.yml`. I use that file to launch my pods easily from Rubymine. I hope it's not a problem!

**Review by akostadinov — APPROVED** [review]

**Comment by mayorova** [comment]
Great! Thanks @jlledom

**Pull request merged**
