### PR TITLE
THREESCALE-9571: Prevent writing immutable fields.

### PR DESCRIPTION
**Pull request by jlledom**
**What this PR does / why we need it**:

To update one resource you can:

1. GET the resource.
2. Update some fields on the received JSON.
3. Copy and paste the modified JSON on a new PUT request.

This fails because the endpoints reject parameters not permitted or whitelisted.
This PR adds some params to the white list. In particular:

File PUT autogenerated attributes: `created_at`, `updated_at`, `url`, `title`, `content_type`
Section PUT autogenerated attributes: `created_at`, `updated_at`
Partial PUT autogenerated attributes: `created_at`, `updated_at`, `published`
Page PUT autogenerated attributes: `created_at`, `updated_at`, `hidden`, `published`
Layout PUT autogenerated attributes: `created_at`, `updated_at`, `published`

**Which issue(s) this PR fixes** 

[THREESCALE-9571](https://issues.redhat.com/browse/THREESCALE-9571)

**Verification steps** 

1. GET the resource.
2. Update some fields on the received JSON.
3. Copy and paste the modified JSON on a new PUT request.
4. Check that immutable fields are ignored.

### CODE REVIEW

**Comment by mayorova** [comment]
@jlledom would you mind adding some docs (comments) to the ForbidParams module explaining how it works? For me it's not intuitive...

Does it reject the request with the params? What does the whitelist do? Does it allow for the params to be set? Or does it ignore them (i.e. the API call having them is not rejected, but the values are not updated in the DB).

**Comment by akostadinov** [comment]
Thi runs a litlle bit contrary to the original idea. Who requested this?

**Comment by jlledom** [comment]
> Thi runs a litlle bit contrary to the original idea. Who requested this?

Martin, here: https://issues.redhat.com/browse/THREESCALE-8993

**Comment by jlledom** [comment]
> @jlledom would you mind adding some docs (comments) to the ForbidParams module explaining how it works? For me it's not intuitive...

I added a comment.

> Does it reject the request with the params? What does the whitelist do? Does it allow for the params to be set? Or does it ignore them (i.e. the API call having them is not rejected, but the values are not updated in the DB).

When you set the permitted params using Strong Parameters, you can call `forbid_extra_params` to decide what to do when the client sends unpermitted parameters. You can chose an `:action` and set a `:whitelist`.

The `:action` can be `:log`, which writes the list of unpermitted parameters on the log; or `:reject`, which returns an error response to the client.

The `:whitelist` contains unpermitted parameters we want to ignore. Receiving these parameters don't trigger the `:aciton`, but the are still unpermitted and don't reach the database.

**Comment by mayorova** [comment]
Great, thank you @jlledom

**Comment by jlledom** [comment]
Closing. After a debate we decided to not do this

**Pull request closed without merging**
