### PR TITLE
Fix Cuke Master Step ensuring that master exists or creates it

### PR DESCRIPTION
**Pull request by Martouta**
Fixes the random failure [in CircleCI](https://circleci.com/gh/3scale/porta/105017#tests/containers/18) with title `failed The 404 page` and in `features/percy/provider.feature:5:in Given the master account allows signups`

### CODE REVIEW

**Comment by hallelujah** [comment]
Approved but I wonder
If you rin this cuke alone with an empty DB it should always fail no?
How can this be random? It should be another cuke or step that deletes the master account aomehow or makes it invalid

**Comment by Martouta** [comment]
Executed in isolation works locally in the current master. I think because of this:
https://github.com/3scale/porta/blob/434182f7f4889f04fe4efbdd26e052be22034f5b/features/support/initial_data.rb#L13
So in this CircleCI failure, maybe another feature removed master :woman_shrugging:

**Comment by hallelujah** [comment]
We should look at which feature removed master or makes it invalid

**Comment by Martouta** [comment]
Makes sense :+1: I will make a Jira issue to check this after 2.7 ER1

**Pull request merged**
