### PR TITLE
fix THREESCALE-3922 Service Plan Features Delete

### PR DESCRIPTION
**Pull request by samu91gn**
**What this PR does / why we need it**:

> Fix for [THREESCALE-3922](https://issues.redhat.com/browse/THREESCALE-3922)

### CODE REVIEW

**Comment by Martouta** [comment]
@samu91gn please run `bundle exec rake doc:swagger:generate:all` to generate the docs 😄

**Comment by samu91gn** [comment]
> please run `bundle exec rake doc:swagger:generate:all` to generate the docs

Hi @Martouta thanks for the tip, I was already doing that while testing, however [this change](https://github.com/3scale/porta/pull/1870/files#diff-994705259cd057d0e7a9987e7027fc51) was required in order for the "Service Plan Features Delete" to appear in the docs; am I missing something? Cheers.

**Comment by Martouta** [comment]
`bundle exec rake doc:swagger:generate:all` generates the docs in the files where we actually read them. The comments in app/controller are just comments used for the gem to generate this documentation once you run that 😄 

This means that this PR needs these 2 things:
1. The change you already made 👍 
2. The changes generated by running `bundle exec rake doc:swagger:generate:all` with the change in the comment already in this PR.

So just go to this branch, with the change that you already made, then run `bundle exec rake doc:swagger:generate:all`, it will generate the documentation files from your change, and then you can add it to the commit by: `git add -A && git commit --amend --no-edit && git push -f`

**Comment by samu91gn** [comment]
I see @Martouta , done! I thought the docs were going to be auto generated somehow. Thanks again!

**Pull request merged**
