### PR TITLE
use jemalloc or memkind when present

### PR DESCRIPTION
**Pull request by akostadinov**
jemalloc has a performance and size advantage when running
Ruby on Rails. So use it when available in the container.

container image `quay.io/3scale/porta:jemalloc-20221021`

### CODE REVIEW

**Comment by jlledom** [comment]
I need some help to understand the context: I assume making this changes on the entry point means that the container image can be built from different Dockerfiles, that may or not have jemalloc installed, right?

**Comment by akostadinov** [comment]
Yes, especially there will be difference between rhel8 and rhel7 images. So to easily build from same codebase. I need to fix codeclimate.

**Comment by mayorova** [comment]
IMO, we shouldn't have this conditional logic at entrypoint.

Instead, I think we need to build the image with the libraries available in the base, and export LD_PRELOAD on the image itself, i.e. update the corresponding Dockerfiles.

This change then could (should) go to Release Notes for the corresponding release.

**Comment by akostadinov** [comment]
The thing is that we may not want every process in the container to run with the alternative jemalloc.

**Comment by akostadinov** [comment]
@mayorova , can you explain your concerns? There are other options but first need to know.

**Review by mayorova — APPROVED** [review]
:+1:

**Pull request merged**
