### PR TITLE
[THREESCALE-7134] Removing SandboxProviderConfGenerator class since it is used only in ApicastV1DeploymentService class

### PR DESCRIPTION
**Pull request by HemaHG**
**What this PR does / why we need it**:
   Removing SandboxProviderConfGenerator class since it is used only in ApicastV1DeploymentService class

**Which issue(s) this PR fixes** 
    part of [THREESCALE-7134](https://issues.redhat.com/browse/THREESCALE-7134)
    
   Depends on https://github.com/3scale/porta/pull/2500

### CODE REVIEW

**Review by josemigallas — CHANGES_REQUESTED** [review]
If I'm not mistaken these lines also need to be removed:
https://github.com/3scale/porta/blob/700fb873a1656669118e33d39ce2c6762c3af2ca/test/unit/services/apicast_v1_deployment_service_test.rb#L76-L82

**Review by akostadinov — CHANGES_REQUESTED** [review]
It also seems that this also needs to be removed:
https://github.com/3scale/porta/blob/d4d13db5129fd6e0e36a6b7e3b335b5ac8e2ffc5/app/services/apicast_v1_deployment_service.rb#L17

**Comment by HemaHG** [comment]
ApicastV1Deploymentservice class is already removed in https://github.com/3scale/porta/pull/2500PR, waiting for that PR to merge

**Comment by akostadinov** [comment]
Seems merged already. Maybe this one needs rebase.

**Review by akostadinov — APPROVED** [review]
I don't see any further refs of `SandboxProviderConfGenerator`. LGTM

**Review by josemigallas — APPROVED** [review]

**Pull request merged**
