### PR TITLE
THREESCALE-8459 upgrade to ruby 2.7

### PR DESCRIPTION
**Pull request by akostadinov**

### CODE REVIEW

**Comment by mayorova** [comment]
When I looked into it a while ago, it seemed that we also needed to upgrade some dependencies: https://github.com/mayorova/porta/commit/1bd9562865487cc0d8aa1cf574c7186160461c4d

I am not sure if it's still relevant, but just mentioning it here.

**Comment by akostadinov** [comment]
There are a couple of deps that need upgrading. But they just throw warnings, nothing broke at least in the test suite.
So it can be done in separate PRs.

**Comment by mayorova** [comment]
The weird thing is that I didn't actually see warnings when I ran this branch locally :shrug: 

That's why I am not sure that is needed.

Also, I didn't see any 2.7 warnings related to keywords params, which is also weird. But maybe I didn't search well enough :grimacing:

**Comment by akostadinov** [comment]
If you look at CircleCi test logs, you should see plenty.

**Review by jlledom — APPROVED** [review]

**Pull request merged**
