### PR TITLE
👷 Disable Eslint in Codeclimate

### PR DESCRIPTION
**Pull request by josemigallas**
We already run the same command in Circleci.

### CODE REVIEW

**Review by jlledom — DISMISSED** [review]

**Review by nidhi-soni1104 — DISMISSED** [review]
LGTM

**Comment by nidhi-soni1104** [comment]
juts fix code climate

**Comment by akostadinov** [comment]
codeclimate issue is rather strange

**Comment by josemigallas** [comment]
> codeclimate issue is rather strange

I think my fork was missing a rebase.

**Comment by akostadinov** [comment]
maybe they don't read config from fork branches - only from main repo. Like circleci

**Comment by josemigallas** [comment]
> maybe they don't read config from fork branches - only from main repo. Like circleci

I created a branch in the original repo and it's still not working 😕 The only explanation possible is that plugin cannot be disabled

**Comment by josemigallas** [comment]
Already merged in https://github.com/3scale/porta/pull/3106

**Pull request closed without merging**
