### PR TITLE
Updates INSTALL.md

### PR DESCRIPTION
**Pull request by lvillen**
**What this PR does / why we need it**:

Updates Ruby and Node versions and updates outdated `brew` command.

### CODE REVIEW

**Comment by josemigallas** [comment]
@lvillen 
LFTM. If this is a work in progress tho please consider adding `[WIP]` at the beginning of the title or make it a _draft pull request_.

**Review by jkeam — APPROVED** [review]
Looks good to me.

**Review by nidhi-soni1104 — APPROVED** [review]

**Comment by nidhi-soni1104** [comment]
@lvillen I think yes you can add it

**Comment by nidhi-soni1104** [comment]
Also you have to manually  approve first two test to run them

**Review by akostadinov — APPROVED** [review]

**Comment by akostadinov** [comment]
Good point about tests. Before merging anything, it is mandatory to run mysql and js tests. But for a doc change, this is not needed. So lets save a few cents.

**Pull request merged**
