### PR TITLE
[email-async] Generate email async for lost password token

### PR DESCRIPTION
**Pull request by hallelujah**
We do not want to keep the web server busy sending email

Requires: https://github.com/3scale/deploy/pull/721

Tested and working

image

Part of THREESCALE-7574

### CODE REVIEW

**Review by akostadinov — DISMISSED** [review]

**Review by akostadinov — DISMISSED** [review]
Looks nice.

**Comment by akostadinov** [comment]
btw do we notify user of sending failures with this background sending? I wonder if we should or should not.

**Comment by hallelujah** [comment]
@akostadinov I do not understand you. What kind of notification would you like the end-user to receive?

**Comment by akostadinov** [comment]
You are right. Exposing whether an email has been sent or not is not good :/

**Review by akostadinov — APPROVED** [review]

**Pull request merged**
